---
- name: Add group for activemq
  group:
    name: '{{ amq_user }}'

- name: Add user for activemq
  user:
    name: '{{ amq_user }}'
    group: '{{ amq_user }}'
    shell: /bin/sh
    createhome: yes
    comment: 'activemq service user'

- name: Create install directory
  file:
    path: '{{ amq_install_dir }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: 0775

- name: Create tmp directory
  file:
    path: '{{ amq_tmp_dir }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: 0775

- name: Download activemq
  get_url:
    url: '{{ amq_download_url }}'
    dest: '{{ amq_tmp_dir }}/amq.tar.gz'
    force: yes
  retries: 5
  delay: 10

- name: Unarchive activemq
  shell: 'tar -xf {{ amq_tmp_dir }}/amq.tar.gz -C {{ amq_install_dir }} --strip-components=1'
  args:
    chdir: '{{ amq_tmp_dir }}'

- name: Copy activemq config file
  template:
    src: activemq.xml.j2
    dest: '{{ amq_install_dir }}/conf/activemq.xml'
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: 0644
  tags:
     - config

- name: Set non-root user for activemq
  lineinfile:
    dest: '{{ amq_install_dir }}/bin/activemq'
    regexp: '^(.*)ACTIVEMQ_USER=""'
    line: '  ACTIVEMQ_USER={{ amq_user }}'
  tags:
     - config

- name: Change owner on install directory
  file:
    path: '{{ amq_install_dir }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    recurse: yes

- name: Clean install files
  file:
    path: '{{ amq_tmp_dir }}'
    state: absent

- name: Symlink init script
  file:
    src: '{{ amq_install_dir }}/bin/activemq'
    dest: '/etc/init.d/activemq'
    state: link

- name: Update rc.d defaults
  shell: 'update-rc.d activemq defaults'
