---
- name: Add group 'activemq'
  group: name={{ amq_user }}

- name: Add user 'activemq'
  user:
    name: '{{ amq_user }}'
    group: '{{ amq_user }}'
    shell: /bin/sh
    createhome: no
    comment: 'activemq service user'

- name: Create install directory
  file:
    path: '{{ amq_install_dir }}/apache-activemq-{{ amq_version }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: 0775

- name: Unarchive activemq
  unarchive:
    src: '{{ amq_download_url }}'
    dest: '{{ amq_install_dir }}'
    copy: no
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    creates: no

- name: Copy activemq config file
  template:
    src: activemq.xml.j2
    dest: '{{ amq_install_dir }}/apache-activemq-{{ amq_version }}/conf/activemq.xml'
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: 0644
  tags:
     - config

- name: Set non-root user for activemq
  lineinfile:
    dest: '{{ amq_install_dir }}/apache-activemq-{{ amq_version }}/bin/activemq'
    regexp: '^(.*)ACTIVEMQ_USER=""'
    line: '  ACTIVEMQ_USER={{ amq_user }}'
  tags:
     - config

- name: Change owner on install directory
  file:
    path: '{{ amq_install_dir }}/apache-activemq-{{ amq_version }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    recurse: yes

- name: Symlink init script
  file:
    src: '{{ amq_install_dir }}/apache-activemq-{{ amq_version }}/bin/activemq'
    dest: '/etc/init.d/activemq'
    state: link

- name: Update rc.d defaults
  shell: 'update-rc.d activemq defaults'
