---
- name: Add group for activemq
  group:
    name: '{{ amq_user }}'
    state: present

- name: Add user for activemq
  user:
    name: '{{ amq_user }}'
    group: '{{ amq_user }}'
    home: '{{ amq_install_dir }}'
    createhome: no
    comment: 'ActiveMQ service user'
    state: present

- name: Create directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    mode: '{{ item.mode }}'
  with_items:
    - { path: '{{ amq_install_dir }}', mode: '0775' }
    - { path: '{{ amq_data_dir }}', mode: 'u=rwx,g=rx,o=x' }
    - { path: '{{ amq_conf_dir }}', mode: '0775' }
    - { path: '{{ amq_tmp_dir }}', mode: '0775' }
    - { path: '/var/log/activemq-instance-{{ amq_broker_instance_name }}', mode: '0755' }
    - { path: '{{ amq_download_tmp_dir }}', mode: '0755' }

- name: Download activemq
  get_url:
    url: '{{ amq_download_url }}'
    dest: '{{ amq_download_tmp_dir }}/amq.tar.gz'
    force: yes
  retries: 5
  delay: 10
